In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("final_results.parquet")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409856 entries, 0 to 409855
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      409856 non-null  int64
 1   target  409856 non-null  object
dtypes: int64(1), object(1)
memory usage: 6.3+ MB

In [21]:
df.describe

<bound method NDFrame.describe of             ID target
0            0      0
1            1      0
2            2      0
3            3      0
4            4      0
...        ...    ...
409851  409851      0
409852  409852      0
409853  409853      0
409854  409854      0
409855  409855      0

[409856 rows x 2 columns]>

In [5]:
df2 = pd.read_parquet('sample_submission.parquet')

In [24]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      50 non-null     int64
 1   target  50 non-null     object
dtypes: int64(1), object(1)
memory usage: 932.0+ bytes

In [3]:
df.head()

   ID target
0   0      0
1   1      0
2   2      0
3   3      0
4   4      0

In [8]:
df.shape

(409856, 2)

In [4]:
df

            ID target
0            0      0
1            1      0
2            2      0
3            3      0
4            4      0
...        ...    ...
409851  409851      0
409852  409852      0
409853  409853      0
409854  409854      0
409855  409855      0

[409856 rows x 2 columns]

In [13]:
import pandas as pd

# 1. Load the REAL test file (the one that actually has 409,856 rows)
df_test = pd.read_parquet("test.parquet") 

# 2. Load your results
df_my_results = pd.read_parquet("final_results.parquet")

# 3. Create the submission using the IDs from the FULL test set
final_submission = pd.DataFrame()
final_submission['ID'] = df_test['ID'].values
final_submission['target'] = df_my_results['target'].values

# 4. Check the head - the IDs should now be correct
print(final_submission.head())
print(f"Final Shape: {final_submission.shape}") # This MUST be (409856, 2)

# 5. Save and Upload
final_submission.to_parquet('final_results_fixed.parquet', index=False)

   ID target
0   0      0
1   1      0
2   2      0
3   3      0
4   4      0
Final Shape: (409856, 2)

In [15]:
final_submission.head()

   ID target
0   0      0
1   1      0
2   2      0
3   3      0
4   4      0

In [20]:
# Convert the target column to integers
final_submission['target'] = final_submission['target'].astype(int)

# Now try the sum again
print(f"Total count of 1s: {final_submission['target'].sum()}")

Total count of 1s: 3104

In [25]:
# 1. Convert Target to integer
final_submission['target'] = final_submission['target'].astype(int)

# 2. Convert ID to integer (just in case it's still a float like 0.0)
final_submission['ID'] = final_submission['ID'].astype(int)

# 3. Double check the sum - it should be a normal number now
print(f"Total 1s: {final_submission['target'].sum()}")

# 4. Save to parquet
final_submission.to_parquet('final_results_fixed.parquet', index=False)

Total 1s: 3104

In [26]:
final_df = pd.read_parquet('final_results_fixed.parquet')

In [27]:
final_df.shape

(409856, 2)

In [28]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409856 entries, 0 to 409855
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      409856 non-null  int64
 1   target  409856 non-null  int64
dtypes: int64(2)
memory usage: 6.3 MB